import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layouts/sidebar";
import Header from "@/components/layouts/header";

const studentMenuItems = [
  { index: 1, path: 'dashboard', label: 'Dashboard', icon: "Home" },
  { index: 2, path: 'my-courses', label: 'My Courses', icon: "BookOpen", count: 14 },
  { index: 3, path: 'courses', label: 'Browse Course', icon: "GraduationCap" },
];

const instructorMenuItems = [
  { index: 1, path: 'dashboard', label: 'Dashboard', icon: "Home" },
  { index: 2, path: 'my-courses', label: 'My Courses', icon: "BookOpen", count: 14 },
  { index: 3, path: 'create-course', label: 'Create Course', icon: "CirclePlus" },
];

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <div>
          <Header />

          <div className="flex h-[93vh]">
            <Sidebar menu={instructorMenuItems} />

            <main className="p-6 basis-full overflow-y-auto">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
